### ISSUE TITLE
Great Readme

### ISSUE THREAD

**Issue by olivermccarthy** [Boostport/kubernetes-vault#121] opened 2018-04-26 13:28 UTC
Hi I get this client token generated
{"clientToken":"$VAULT_TOKEN","accessor":"$ACCESS_TOKEN","leaseDuration":21600,"renewable":true,"vaultAddr":"http://vault:8200"}

How can I use curl to access secrets etc in vault using this token.
I assume your sample app uses the token to perform some actions. 
 curl     --header "X-Vault-Token: $VAULT_TOKEN"        http://vault:8200/  ?

**Comment by F21** [comment] 2018-04-26 22:50
Hey @olivermccarthy, that's correct. Once you have the vault token, you can use any method you like (curl, vault go client, etc) to access vault.

**Comment by olivermccarthy** [comment] 2018-04-27 08:47
Thank you
Im not seeing that token working for me. Im following the quick start guide.
You can see default token works. Token in /var/run/secrets/boostport.com/vault-token does not


curl --header "X-Vault-Token: vault-root-token" http://vault:8200/v1/cubbyhole
{"request_id":"6ab94713-6059-600d-55b8-9b8e975960f0","lease_id":"","renewable":false,"lease_duration":0,"data":{"excited":"yes","foo":"world"},"wrap_info":null,"warnings":null,"auth":null}

cat /var/run/secrets/boostport.com/vault-token 
{"clientToken":"856055d2-d04f-f62e-4691-a566d9d62a7a","accessor":"b7d5336e-da8a-4661-e0ae-7f36f7d15536","leaseDuration":10800,"renewable":true,"vaultAddr":"http://vault:8200"}root@sample-app-79f96b7db9-j76vh
curl --header "X-Vault-Token: 856055d2-d04f-f62e-4691-a566d9d62a7a" http://vault:8200/v1/cubbyhole
{"errors":["permission denied"]}








vault read  auth/approle/role/sample-app/
Key                   Value
---                   -----
bind_secret_id        true
bound_cidr_list       []
period                21600
policies              [kubernetes-vault]
secret_id_num_uses    1
secret_id_ttl         90
token_max_ttl         0
token_num_uses        0
token_ttl             0

**Comment by F21** [comment] 2018-04-27 10:02
Thanks for the debugging. I believe the problem is that the sample app does not have permissions to use the cubby hole. You will need to update the policy file to give the sample-app access to the cubbyhole: https://github.com/Boostport/kubernetes-vault/blob/master/deployments/quick-start/policy-sample-app.hcl

**Comment by olivermccarthy** [comment] 2018-04-27 10:28
Hi I was able to login using the secret id
But then the token does not seem to work. default policy allows reading from cubbyhole

vault write auth/approle/login role_id=166e41f3-996a-d951-9b4b-8d55e66644c4 secret_id=060691a8-
3a57-66c0-5ac7-38e13801104b
Key                     Value
---                     -----
token                   93ae1bf5-23ef-cd2a-dfdc-e89f2fd34d4a
token_accessor          c84fd0de-ffa7-f1d7-b533-a95e289f7f7e
token_duration          20m
token_renewable         true
token_policies          [default]
token_meta_role_name    my-role
export VAULT_TOKEN='93ae1bf5-23ef-cd2a-dfdc-e89f2fd34d4a'
vault read cubbyhole
rror reading cubbyhole: Error making API request.

URL: GET http://127.0.0.1:8200/v1/cubbyhole
Code: 403. Errors:

* permission denied

**Comment by F21** [comment] 2018-04-27 11:19
Hey,

According to the docs, you need to grant permission to access the cubbyhole. See https://www.vaultproject.io/guides/secret-mgmt/cubbyhole.html#additional-discussion

**Comment by olivermccarthy** [comment] 2018-04-27 12:59
Cheers
 Its vault read cubbyhole/private I should have been doing

**Comment by F21** [comment] 2018-04-28 02:59
Awesome! I will close this issue since it's been resolved 😄

**Closed as completed by F21** 2018-04-28 02:59 UTC
