### ISSUE TITLE
Validate secrets is slow when init container

### ISSUE THREAD

**Issue by suaha** [Boostport/kubernetes-vault#150] opened 2019-05-31 02:42 UTC
We have more than 80 pods which are using kubernetes-vault, we are using kubernetes-vault-init:0.5.0 as 1st step of pod's init container.

But this step is randomly slow, say that 3~30+ seconds in our environment. I have went through the store.go and notice that kubernetes-vault-init loop all pods to validate secrets one by one, it might be the root cause of the slowness, because we have 80+ pods here.

Let us examine below code:

/cmd/controller/cluster/store.go
func (s *Store) getPodsAndPushSecretIds() {
	pods, err := s.kubeClient.GetPods()

	if err != nil {
		s.logger.Errorf("Could not list pods: %s", err)
	}

	s.Lock()
	for _, pod := range pods {
		if _, ok := s.pods[pod.Name]; !ok {
			s.pods[pod.Name] = pod

			go s.pushSecretIdToPod(pod)
		}
	}
	s.Unlock()
}

/cmd/init/main.go
	go startHTTPServer(certificate, logger, result)

	for {
		select {
		case wrappedSecretId := <-result:

			if err := wrappedSecretId.Validate(); err != nil {
				logger.Fatalf("could not validate wrapped secret_id: %s", err)
			}

It seems that the init time is related to the number of pods, correct me if I am wrong.

So is there any way to reduce init container time? You know, 3 seconds is still slow....

**Comment by F21** [comment] 2019-05-31 03:00
It's hard to tell without access to your environment. It could be that there isn't enough resources in the cluster or there is high load causing things to start slowly.

You seem to be using a pretty old version. Can you try v0.6.1 to see if it improves?

If v0.6.1 does not yield any improvement, I'd suggest compiling your own version of the controller with some debugging statements added to [`getPodsAndPushSecretsIds()`](https://github.com/Boostport/kubernetes-vault/blob/master/cmd/controller/cluster/store.go#L238) to see if the loop is the main cause of the slow down. It would be a good idea to add a few `fmt.Println(time.Now())` statements to the method as well as to [`pushSecretIdToPod`](https://github.com/Boostport/kubernetes-vault/blob/master/cmd/controller/cluster/store.go#L255) to see if you can pinpoint the cause of the slowness.

**Comment by suaha** [comment] 2019-05-31 03:24
Thanks for your quick response.

1. I am pretty sure there is no load in our environment
2. It's a good idea to add some logs to see if the slowness comes from getPods， I'll do it.

**Comment by suaha** [comment] 2019-06-05 07:30
Hi, I added logs to several places and did test again, the log indicates that getPods is not slow.
Actually, I don't see any slowness in controller and no slowness in vault-init as well. But I do observe that there is ~13 seconds delay between vault-init completed and controller push secret. I have no idea why.....

Is there any interval for kubenetes api watching?

**Comment by F21** [comment] 2019-06-05 08:45
~~This is the code that does the watching: https://github.com/Boostport/kubernetes-vault/blob/master/cmd/controller/client/kube.go#L78~~

~~From my understanding, there is no configured interval for watch (if there is any, it would be using the default values).~~

We are polling every 20 seconds here as a fallback, if the watcher fails: https://github.com/Boostport/kubernetes-vault/blob/44be8b20dcdc67178c4fad40ab9bdfc5e2cd9608/cmd/controller/cluster/store.go#L191

I think it's probably a problem with the watcher not seeing pods.

Can you add logs to the following to see why the watcher fails?
- https://github.com/Boostport/kubernetes-vault/blob/master/cmd/controller/client/kube.go#L68
- https://github.com/Boostport/kubernetes-vault/blob/master/cmd/controller/client/kube.go#L78

Also, do you see any logs signaling an error for the kubernetes-vault controller?

**Comment by F21** [comment] 2019-06-17 23:22
@suaha Did you guys ended up resolving this?

**Comment by suaha** [comment] 2019-06-24 09:37
I'm sorry for the late response, we are busy on release these days so I did not do the test for this issue, I will do it this week.

**Comment by suaha** [comment] 2019-07-08 02:14
We added some logs on both client and controller, it proves that the watch pod method does not work properly.

On client, the http server started at 9:58:37
time="2019-07-05T09:58:37Z" level=info msg="Get logger."
time="2019-07-05T09:58:37Z" level=info msg="Get vault role id."
time="2019-07-05T09:58:37Z" level=info msg="Get timeout setting."
time="2019-07-05T09:58:37Z" level=info msg="Retrieve token."
time="2019-07-05T09:58:37Z" level=info msg="Get unwarp secret."
time="2019-07-05T09:58:37Z" level=info msg="Get credential path."
time="2019-07-05T09:58:37Z" level=info msg="Get external ip."
time="2019-07-05T09:58:37Z" level=info msg="Generated self-signed certificate."
**time="2019-07-05T09:58:37Z" level=info msg="Started http server."**
**time="2019-07-05T09:58:45Z" level=info msg="Receive wrappedSecretId."**
time="2019-07-05T09:58:45Z" level=info msg="Validated wrapped secret id."
time="2019-07-05T09:58:45Z" level=info msg="Get api client."
time="2019-07-05T09:58:46Z" level=info msg=Login.
time="2019-07-05T09:58:46Z" level=info msg="ReadFile /var/run/secrets/kubernetes.io/serviceaccount/namespace."
time="2019-07-05T09:58:46Z" level=warning msg="The namespace of approle is not equal to kubernetes"
time="2019-07-05T09:58:46Z" level=info msg="Successfully generate trustedCAs. Exiting."
time="2019-07-05T09:58:46Z" level=info msg="Successfully generate issue_ca. Exiting."
time="2019-07-05T09:58:46Z" level=info msg="Successfully created the vault token. Exiting."

On controller side:
**time="2019-07-05T09:57:05Z" level=error msg="Start to s.kubeClient.WatchForPods"**
time="2019-07-05T09:57:25Z" level=error msg="case pollPodsTicker"
time="2019-07-05T09:57:45Z" level=error msg="case pollPodsTicker"
time="2019-07-05T09:58:05Z" level=error msg="case pollPodsTicker"
time="2019-07-05T09:58:25Z" level=error msg="case pollPodsTicker"
**time="2019-07-05T09:58:45Z" level=error msg="case pollPodsTicker"**
**time="2019-07-05T09:58:45Z" level=error msg="getPodsAndPushSecretIds pushSecretIdToPod"**

The time is matched on both client side and controller side, so actually it will be maximum 20 seconds delay. One interesting finding is that the 'case pod := <-events' never be hit, it always goes into 		'case <-pollPodsTicker.C' 

@F21 Could you please have a check on this?

**Comment by F21** [comment] 2019-07-08 02:37
The watcher needs to be able to [watch all namespaces](https://github.com/Boostport/kubernetes-vault/blob/44be8b20dcdc67178c4fad40ab9bdfc5e2cd9608//cmd/controller/client/kube.go#L97), Does the service account for the controller have the correct permissions? If you're using RBAC, you will need to use a [ClusterRoleBinding](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#rolebinding-and-clusterrolebinding).

**Closed as completed** 2021-02-23 23:06 UTC
