### ISSUE TITLE
msg="Failed to create vault auth token because we timed out after 5m0s before receiving the secret_id. Exiting."

### ISSUE THREAD

**Issue by ianrossi** [Boostport/kubernetes-vault#131] opened 2018-07-25 15:06 UTC
I'm using the Quick Start `setup.sh` script from the current master and I'm having the same issue as https://github.com/Boostport/kubernetes-vault/issues/26 but Vault and the sample application are both in the same namespace. The init containers of the sample app pods are showing this error.
```
time="2018-07-25T14:57:27Z" level=fatal msg="Failed to create vault auth token because we timed out after 5m0s before receiving the secret_id. Exiting."
```
Is there another reason for this timeout? The Vault pod looks like it's working properly:
```
==> Vault server started! Log data will stream in below:

2018-07-25T13:49:49.211Z [INFO ] core: security barrier not initialized
2018-07-25T13:49:49.211Z [INFO ] core: security barrier initialized: shares=1 threshold=1
2018-07-25T13:49:49.211Z [INFO ] core: post-unseal setup starting
2018-07-25T13:49:49.223Z [INFO ] core: loaded wrapping token key
2018-07-25T13:49:49.223Z [INFO ] core: successfully setup plugin catalog: plugin-directory=
2018-07-25T13:49:49.223Z [INFO ] core: no mounts; adding default mount table
2018-07-25T13:49:49.224Z [INFO ] core: successfully mounted backend: type=kv path=secret/
2018-07-25T13:49:49.224Z [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2018-07-25T13:49:49.224Z [INFO ] core: successfully mounted backend: type=system path=sys/
2018-07-25T13:49:49.224Z [INFO ] core: successfully mounted backend: type=identity path=identity/
2018-07-25T13:49:49.226Z [INFO ] core: restoring leases
2018-07-25T13:49:49.226Z [INFO ] rollback: starting rollback manager
2018-07-25T13:49:49.227Z [INFO ] expiration: lease restore complete
2018-07-25T13:49:49.227Z [INFO ] identity: entities restored
2018-07-25T13:49:49.227Z [INFO ] identity: groups restored
2018-07-25T13:49:49.227Z [INFO ] core: post-unseal setup complete
2018-07-25T13:49:49.227Z [INFO ] core: root token generated
2018-07-25T13:49:49.227Z [INFO ] core: pre-seal teardown starting
2018-07-25T13:49:49.227Z [INFO ] core: cluster listeners not running
2018-07-25T13:49:49.227Z [INFO ] rollback: stopping rollback manager
2018-07-25T13:49:49.227Z [INFO ] core: pre-seal teardown complete
2018-07-25T13:49:49.227Z [INFO ] core: vault is unsealed
2018-07-25T13:49:49.227Z [INFO ] core: post-unseal setup starting
2018-07-25T13:49:49.227Z [INFO ] core: loaded wrapping token key
2018-07-25T13:49:49.227Z [INFO ] core: successfully setup plugin catalog: plugin-directory=
2018-07-25T13:49:49.227Z [INFO ] core: successfully mounted backend: type=kv path=secret/
2018-07-25T13:49:49.227Z [INFO ] core: successfully mounted backend: type=system path=sys/
2018-07-25T13:49:49.228Z [INFO ] core: successfully mounted backend: type=identity path=identity/
2018-07-25T13:49:49.228Z [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2018-07-25T13:49:49.228Z [INFO ] core: restoring leases
2018-07-25T13:49:49.228Z [INFO ] rollback: starting rollback manager
2018-07-25T13:49:49.228Z [INFO ] identity: entities restored
2018-07-25T13:49:49.229Z [INFO ] expiration: lease restore complete
2018-07-25T13:49:49.229Z [INFO ] identity: groups restored
2018-07-25T13:49:49.229Z [INFO ] core: post-unseal setup complete
2018-07-25T13:49:49.230Z [INFO ] expiration: revoked lease: lease_id=auth/token/root/95088888c9b0f4beb060898ebba5b3a2cbd886a4
2018-07-25T13:49:49.232Z [INFO ] core: mount tuning of options: path=secret/ options=map[version:2]
2018-07-25T13:49:49.233Z [INFO ] secrets.kv.kv_7eff7e71: collecting keys to upgrade
2018-07-25T13:49:49.233Z [INFO ] secrets.kv.kv_7eff7e71: done collecting keys: num_keys=1
2018-07-25T13:49:49.233Z [INFO ] secrets.kv.kv_7eff7e71: upgrading keys finished
2018-07-25T13:49:53.678Z [INFO ] core: successful mount: path=root-ca/ type=pki
2018-07-25T13:49:54.779Z [INFO ] core: successful mount: path=intermediate-ca/ type=pki
2018-07-25T13:49:56.396Z [INFO ] core: enabled credential backend: path=approle/ type=approle
```

**Comment by F21** [comment] 2018-07-25 22:59
The reason for that error is because the init container was not pushed a secret. The most likely cause is that the kubernetes-vault controller did not see the pod. Are the sample-app pod and the kubernetes-vault controller in the same namespace?

**Comment by ianrossi** [comment] 2018-07-26 14:56
@F21 Thanks for the reply. Yes, the sample-app pod and controller pod are in the same namespace, see here:
```
$ kubectl get all --namespace irossi --show-all
NAME                            READY     STATUS                  RESTARTS   AGE
po/sample-app-b445fc547-bct8n   0/1       Init:CrashLoopBackOff   221        1d
po/sample-app-b445fc547-mp7tk   0/1       Init:0/1                221        1d
po/sample-app-b445fc547-mz7n8   0/1       Init:CrashLoopBackOff   221        1d
po/sample-app-b445fc547-njvqk   0/1       Init:0/1                221        1d
po/sample-app-b445fc547-s5bcx   0/1       Init:0/1                221        1d
po/vault-79b99bc74-bqz8c        1/1       Running                 0          1d

NAME                   CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
svc/kubernetes-vault   None             <none>                   1d
svc/vault              100.70.122.223   <none>        8200/TCP   1d

NAME                DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/sample-app   5         5         5            0           1d
deploy/vault        1         1         1            1           1d

NAME                      DESIRED   CURRENT   READY     AGE
rs/sample-app-b445fc547   5         5         0         1d
rs/vault-79b99bc74        1         1         1         1d
```

**Comment by ianrossi** [comment] 2018-07-26 15:08
@F21 How is a secret pushed to the init container? I can exec into the Vault controller pod and successfully ping the IP of the sample app pod. Is there a `curl` command I can run to test anything?

**Comment by F21** [comment] 2018-07-26 22:37
The problem is that your kubernetes-vault controller is not seeing the sample app pods. Since, you're using the `irossi` namespace, can you post the contents of your kubernetes-vault controller deployment?

**Comment by ianrossi** [comment] 2018-07-27 18:45
@F21  Here you go:
```
k describe deploy/vault
Name:                   vault
Namespace:              irossi
CreationTimestamp:      Wed, 25 Jul 2018 09:49:45 -0400
Labels:                 app=vault
Annotations:            deployment.kubernetes.io/revision=1
                        kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"vault"},"name":"vault","namespace":"irossi"},"spec...
Selector:               app=vault
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  1 max unavailable, 1 max surge
Pod Template:
  Labels:       app=vault
  Containers:
   vault:
    Image:      vault
    Port:       8200/TCP
    Environment:
      VAULT_DEV_ROOT_TOKEN_ID:  vault-root-token
    Mounts:                     <none>
  Volumes:                      <none>
Conditions:
  Type          Status  Reason
  ----          ------  ------
  Available     True    MinimumReplicasAvailable
OldReplicaSets: <none>
NewReplicaSet:  vault-79b99bc74 (1/1 replicas created)
Events:         <none>
```
And also:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"vault"},"name":"vault","namespace":"irossi"},"spec":{"replicas":1,"template":{"metadata":{"labels":{"app":"vault"}},"spec":{"containers":[{"env":[{"name":"VAULT_DEV_ROOT_TOKEN_ID","value":"vault-root-token"}],"image":"vault","name":"vault","ports":[{"containerPort":8200,"name":"vaultport","protocol":"TCP"}],"securityContext":{"capabilities":{"add":["IPC_LOCK"]}}}]}}}}
  creationTimestamp: 2018-07-25T13:49:45Z
  generation: 1
  labels:
    app: vault
  name: vault
  namespace: irossi
  resourceVersion: "73694959"
  selfLink: /apis/extensions/v1beta1/namespaces/irossi/deployments/vault
  uid: 96a9f44c-9011-11e8-bc13-067f92195cd2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vault
    spec:
      containers:
      - env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: vault-root-token
        image: vault
        imagePullPolicy: Always
        name: vault
        ports:
        - containerPort: 8200
          name: vaultport
          protocol: TCP
        resources: {}
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-07-25T13:49:45Z
    lastUpdateTime: 2018-07-25T13:49:45Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
```

**Comment by F21** [comment] 2018-07-28 07:55
Hmm. That looks like the deployment for vault. Can you post the one for the kubernetes-vault controller?

**Comment by ianrossi** [comment] 2018-07-30 14:17
@F21 I just noticed that the `kubernetes-vault` deployment resource did not get created in the `irossi` namespace, but in the `default` namespace. What is the expected usage of the setup script? Is the expectation that all the created Kubernetes resources are in the same namespace?

**Comment by ianrossi** [comment] 2018-07-30 14:50
@F21 By going through the quick start guide manually and also deploying everything into the default namespace, I was able to make it all work. The way my `kubectl` config is setup is with my own user (`irossi`) namespace--by default everything I deploy there, unless specified otherwise, will end up in my `irossi` namespace.

Question: It seems that the design of kubernetes-vault is that it would be deployed in the `default` namespace (or any other namespace) but still be able to communicate with and push to pods in other namespaces, is this correct?

**Comment by F21** [comment] 2018-07-30 22:45
@ianrossi The quick setup script is meant to allow users to quickly spin things up to kick tires. In a production environment, it's expected that you'd modify it, use your own scripts or the helm chart here: https://github.com/helm/charts/tree/master/incubator/kubernetes-vault

Re: your question regarding kubernetes-vault deployed in `default`, but watching other namespaces. Yes, that is the design. You can deploy kubernetes-vault into any namespace and have it watch any namespace. See the `watchNamespace` setting: https://github.com/Boostport/kubernetes-vault#kubernetes-required

**Comment by F21** [comment] 2018-08-03 00:27
@ianrossi Can this be closed?

**Comment by harneetsinghquark** [comment] 2018-10-10 11:38
I have run into the exact same error and my kubernetes-vault is running is kube-system namespace.
I am able to ping my web-app from kubernetes-vault pods.

the watch-namespace has also been properly set
watchNamespace: '~.*'
  serviceNamespace: kube-system

what could be going wrong
PS: this is on aws EKS, not that it should matter
@F21

**Comment by F21** [comment] 2018-10-10 21:28
Can you post your logs from the Kubernetes-Vault controller? Which version of Kubernetes and Vault are you using?

**Comment by F21** [comment] 2019-01-10 05:18
Closing due to staleness.

**Closed as completed by F21** 2019-01-10 05:18 UTC
