### ISSUE TITLE
Could not create the vault client: error parsing supplied token: failed to lookup Vault periodic token: Get http://vault:8200/v1/auth/token/lookup-self: dial tcp 10.0.29.179:8200: connect: connection refused

### ISSUE THREAD

**Issue by ju187** [Boostport/kubernetes-vault#147] opened 2019-03-11 21:59 UTC
Tried to run the quick start guide.  Each time I deploy the sample app, kubernetes-vault reports this error and crash.
time="2019-03-11T21:50:00Z" level=debug msg="Discovered 0 nodes: []"
time="2019-03-11T21:50:00Z" level=fatal msg="Could not create the vault client: error parsing supplied token: failed to lookup Vault periodic token: Get http://vault:8200/v1/auth/token/lookup-self: dial tcp 10.0.29.179:8200: connect: connection refused"

This is a dev environment and I did not make much change to the configure files.  Any suggestions?

**Comment by F21** [comment] 2019-03-11 22:05
It seems that your Vault server is not running correctly. Can you post the logs from the vault server using `kubectl logs`?

**Comment by ju187** [comment] 2019-03-11 22:19
One thing I should mention is that I didn't start vault in dev mode.  Instead I started and initialized it with key and a token.  Here is the log
==> Vault server started! Log data will stream in below:

2019-03-11T21:12:34.723Z [WARN]  no `api_addr` value specified in config or in VAULT_API_ADDR; falling back to detection if possible, but this value should be manually set
2019-03-11T21:13:28.306Z [INFO]  core: seal configuration missing, not initialized
2019-03-11T21:13:28.306Z [INFO]  core: security barrier not initialized
2019-03-11T21:13:38.428Z [INFO]  core: security barrier not initialized
2019-03-11T21:13:38.429Z [INFO]  core: seal configuration missing, not initialized
2019-03-11T21:13:48.517Z [INFO]  core: security barrier not initialized
2019-03-11T21:13:48.517Z [INFO]  core: seal configuration missing, not initialized
2019-03-11T21:13:58.604Z [INFO]  core: security barrier not initialized
2019-03-11T21:13:58.605Z [INFO]  core: seal configuration missing, not initialized
2019-03-11T21:14:08.698Z [INFO]  core: security barrier not initialized
2019-03-11T21:14:08.699Z [INFO]  core: seal configuration missing, not initialized
2019-03-11T21:14:18.785Z [INFO]  core: security barrier not initialized
2019-03-11T21:14:18.786Z [INFO]  core: seal configuration missing, not initialized
2019-03-11T21:14:28.876Z [INFO]  core: security barrier not initialized
2019-03-11T21:14:28.877Z [INFO]  core: seal configuration missing, not initialized
2019-03-11T21:14:32.418Z [INFO]  core: seal configuration missing, not initialized
2019-03-11T21:14:38.965Z [INFO]  core: security barrier not initialized
2019-03-11T21:14:38.966Z [INFO]  core: seal configuration missing, not initialized
2019-03-11T21:14:49.050Z [INFO]  core: security barrier not initialized
2019-03-11T21:14:49.058Z [INFO]  core: seal configuration missing, not initialized
2019-03-11T21:14:59.139Z [INFO]  core: security barrier not initialized
2019-03-11T21:14:59.140Z [INFO]  core: seal configuration missing, not initialized
2019-03-11T21:15:09.225Z [INFO]  core: security barrier not initialized
2019-03-11T21:15:09.226Z [INFO]  core: seal configuration missing, not initialized
2019-03-11T21:15:19.320Z [INFO]  core: security barrier not initialized
2019-03-11T21:15:19.320Z [INFO]  core: seal configuration missing, not initialized
2019-03-11T21:15:29.405Z [INFO]  core: security barrier not initialized
2019-03-11T21:15:29.406Z [INFO]  core: seal configuration missing, not initialized
2019-03-11T21:15:39.488Z [INFO]  core: security barrier not initialized
2019-03-11T21:15:39.489Z [INFO]  core: seal configuration missing, not initialized
2019-03-11T21:15:49.572Z [INFO]  core: security barrier not initialized
2019-03-11T21:15:49.573Z [INFO]  core: seal configuration missing, not initialized
2019-03-11T21:15:59.657Z [INFO]  core: security barrier not initialized
2019-03-11T21:15:59.658Z [INFO]  core: seal configuration missing, not initialized
2019-03-11T21:16:09.744Z [INFO]  core: security barrier not initialized
2019-03-11T21:16:09.744Z [INFO]  core: seal configuration missing, not initialized
2019-03-11T21:16:19.825Z [INFO]  core: security barrier not initialized
2019-03-11T21:16:19.826Z [INFO]  core: seal configuration missing, not initialized
2019-03-11T21:16:29.916Z [INFO]  core: security barrier not initialized
2019-03-11T21:16:29.916Z [INFO]  core: seal configuration missing, not initialized
2019-03-11T21:16:31.515Z [INFO]  core: security barrier not initialized
2019-03-11T21:16:31.515Z [INFO]  core: security barrier initialized: shares=1 threshold=1
2019-03-11T21:16:31.515Z [INFO]  core: post-unseal setup starting
2019-03-11T21:16:31.528Z [INFO]  core: loaded wrapping token key
2019-03-11T21:16:31.528Z [INFO]  core: successfully setup plugin catalog: plugin-directory=
2019-03-11T21:16:31.528Z [INFO]  core: no mounts; adding default mount table
2019-03-11T21:16:31.529Z [INFO]  core: successfully mounted backend: type=kv path=secret/
2019-03-11T21:16:31.529Z [INFO]  core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2019-03-11T21:16:31.529Z [INFO]  core: successfully mounted backend: type=system path=sys/
2019-03-11T21:16:31.529Z [INFO]  core: successfully mounted backend: type=identity path=identity/
2019-03-11T21:16:31.531Z [INFO]  core: successfully enabled credential backend: type=token path=token/
2019-03-11T21:16:31.531Z [INFO]  core: restoring leases
2019-03-11T21:16:31.531Z [INFO]  rollback: starting rollback manager
2019-03-11T21:16:31.532Z [INFO]  expiration: lease restore complete
2019-03-11T21:16:31.532Z [INFO]  identity: entities restored
2019-03-11T21:16:31.532Z [INFO]  identity: groups restored
2019-03-11T21:16:31.532Z [INFO]  core: post-unseal setup complete
2019-03-11T21:16:31.532Z [INFO]  core: starting listener: listener_address=127.0.0.1:8201
2019-03-11T21:16:31.532Z [INFO]  core: root token generated
2019-03-11T21:16:31.532Z [INFO]  core: pre-seal teardown starting
2019-03-11T21:16:31.532Z [INFO]  core: stopping cluster listeners
2019-03-11T21:16:31.532Z [INFO]  core: shutting down forwarding rpc listeners
2019-03-11T21:16:31.532Z [INFO]  core: forwarding rpc listeners stopped
2019-03-11T21:16:31.532Z [INFO]  core: serving cluster requests: cluster_listen_address=127.0.0.1:8201
2019-03-11T21:16:31.532Z [INFO]  core: rpc listeners successfully shut down
2019-03-11T21:16:31.532Z [INFO]  core: cluster listeners successfully shut down
2019-03-11T21:16:31.532Z [INFO]  rollback: stopping rollback manager
2019-03-11T21:16:31.532Z [INFO]  core: pre-seal teardown complete
2019-03-11T21:18:38.712Z [INFO]  core: vault is unsealed
2019-03-11T21:18:38.712Z [INFO]  core: post-unseal setup starting
2019-03-11T21:18:38.712Z [INFO]  core: loaded wrapping token key
2019-03-11T21:18:38.712Z [INFO]  core: successfully setup plugin catalog: plugin-directory=
2019-03-11T21:18:38.712Z [INFO]  core: successfully mounted backend: type=kv path=secret/
2019-03-11T21:18:38.713Z [INFO]  core: successfully mounted backend: type=system path=sys/
2019-03-11T21:18:38.713Z [INFO]  core: successfully mounted backend: type=identity path=identity/
2019-03-11T21:18:38.713Z [INFO]  core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2019-03-11T21:18:38.714Z [INFO]  core: successfully enabled credential backend: type=token path=token/
2019-03-11T21:18:38.714Z [INFO]  core: restoring leases
2019-03-11T21:18:38.714Z [INFO]  rollback: starting rollback manager
2019-03-11T21:18:38.714Z [INFO]  identity: entities restored
2019-03-11T21:18:38.714Z [INFO]  identity: groups restored
2019-03-11T21:18:38.714Z [INFO]  core: post-unseal setup complete
2019-03-11T21:18:38.714Z [INFO]  core: starting listener: listener_address=127.0.0.1:8201
2019-03-11T21:18:38.714Z [INFO]  core: serving cluster requests: cluster_listen_address=127.0.0.1:8201
2019-03-11T21:18:38.714Z [INFO]  expiration: lease restore complete
2019-03-11T21:21:06.951Z [INFO]  core: successful mount: namespace= path=root-ca/ type=pki
2019-03-11T21:21:56.141Z [INFO]  core: successful mount: namespace= path=intermediate-ca/ type=pki
2019-03-11T21:29:24.729Z [INFO]  core: enabled credential backend: path=approle/ type=approle

**Comment by F21** [comment] 2019-03-11 22:21
The problem is that Vault listener is started on `127.0.0.1:8201`. Your Kubernetes-Vault config expects Vault to be at `10.0.29.179:8200`, but since Vault is listening on its loopback address, it will not be reachable.

**Comment by ju187** [comment] 2019-03-12 06:35
I tried not to start vault in dev mode so added a line in vault.yaml
command: ["vault", "server", "-config", "/vault/config/config.json"]
The config.json is
{
"listener": {
    "tcp":{
      "address": "127.0.0.1:8200",
      "tls_disable": 1
    }
  },
  "storage": {"inmem":{}
  },
  "ui": true
}
If I didn't set listener, it did not work either.  Any suggestion how to set the listener address?  Much appreciated

**Comment by F21** [comment] 2019-03-12 06:37
Try setting the address to `0.0.0.0:8200`. This will tell it to listen to all interfaces.

**Comment by ju187** [comment] 2019-03-12 15:47
Tried that and seems worked.  However the sample app pod all have status init, but the pods did have tokens;  Logs are
sample-app-57bb645f76-5q2lj                         0/1     Init:0/1           0          3s
sample-app-57bb645f76-jbszd                         0/1     Init:0/1           0          3s
sample-app-57bb645f76-lrx5b                         0/1     Init:0/1           0          3s
sample-app-57bb645f76-r58s5                         0/1     Init:0/1           0          3s
sample-app-57bb645f76-x4v2c                         0/1     Init:0/1           0          3s

Found Vault token...
Token:           s.Ah6aRMoI5a4dbDsJTTSUOGGm
Accessor:        WrkDRhg0hjOIPwj9zX5ZG4ke
Lease Duration:  21600
Renewable:       true
Vault Address:   http://vault:8200
Sample App v0.6.1 (503d2759d5e925c79891b9601427e0329e1a8369) built on Mon Nov 26 22:44:38 UTC 2018
CA Bundle Exists:  false

Then in production, I probably don't want to let it listens on all interface.  Should I specify a cluster_addr and let my app listening on that address?  Like using cluster address instead of http://vault:8200?  Thanks

**Comment by F21** [comment] 2019-03-12 21:02
I am not sure why the pods are showing as status init, perhaps this is because the status is lagging? If the app pods received the token, then everything should work correctly.

If you won't want to listen on `0.0.0.0`, you can use Kubernetes' [downward API](https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#capabilities-of-the-downward-api). The `status.podIP` property might allow you to bind to the pod's IP address.

If you are using a service mesh such as istio, I think all communication is on `127.0.0.1`, so that might work. It's been a while since I looked at istio, so the details are hazy.

**Comment by ju187** [comment] 2019-03-13 04:57
Have an unrelated question.  Tried to build the sample-app image without push as I wanted to play around with the code.  It was on a Mac and the images always crashed with error
standard_init_linux.go:190: exec user process caused "exec format error"

This is before I made any code changes

**Comment by F21** [comment] 2019-03-13 05:00
Can you post the commands you used and the logs/output of the build?

**Comment by ju187** [comment] 2019-03-13 05:35
Here is the build-dev-image.sh.  I created a repository so changed the tag and only build sample-app container.  As for the log file, I did not find log/output under the kubernetes-vault directory.  Thanks
#!/bin/sh
  
VERSION=dev

# Build the binaries
docker run --rm -v "$PWD":/source/kubernetes-vault -w /source/kubernetes-vault golang:1.11-alpine ./build.sh

# Build the images
#docker build -t daywalker128/mydepot/kubernetes-vault:"$VERSION" -f cmd/controller/Dockerfile.dev cmd/controller/
#docker build -t daywalker128/mydepot/kubernetes-vault-init:"$VERSION" -f cmd/init/Dockerfile.dev cmd/init/
docker build -t daywalker128/mydepot/kubernetes-vault-sample-app:"$VERSION" -f cmd/sample-app/Dockerfile.dev cmd/sample-app/

# Push images
#docker push daywalker128/mydepot/kubernetes-vault:"$VERSION"
#docker push daywalker128/mydepot/kubernetes-vault-init:"$VERSION"
#docker push daywalker128/mydepot/kubernetes-vault-sample-app:"$VERSION"

**Comment by F21** [comment] 2019-03-13 06:01
Hmm. It's hard to tell what the problem it. According to this thread, it's because you're trying to build on an unsupported architecture: https://forums.docker.com/t/standard-init-linux-go-190-exec-user-process-caused-exec-format-error/49368

If your docker is really old, I'd suggest upgrading it to the latest version.

My other suggestion is to repull the image after purging using `docker system prune --all`.

Also, check that the line endings of all files are LF.

**Comment by ju187** [comment] 2019-03-13 07:11
purge the repository did the trick.  Really appreciate it.  Thanks

**Comment by F21** [comment] 2019-03-13 11:18
Glad you got it working. I am going to go ahead and close this issue.

**Closed as completed by F21** 2019-03-13 11:18 UTC

**Comment by DrissiReda** [comment] 2020-01-02 10:00
I have the same problem as the title, but not the same logs output. I ran etcd and vault on kubernetes, managed to get them working. But when I deploy kubernetes-vault I get connection refused.
